### PR TITLE
samba ad dc fixes

### PR DESCRIPTION
**Pull request by dmulder**

### CODE REVIEW

**Comment by dmulder** [comment]
I discovered a couple issues after submitting yesterday.
1. I did a sloppy search and replace in the Dockerfile, which broke the build.
2. I didn't sufficiently test provisioning a DC in an existing domain.

These are now fixed with these patches.

**Comment by dmulder** [comment]
@thkukuk could you take a look?

**Comment by thkukuk** [comment]
I added you as maintainer now, so that you can maintain your Dockerfile yourself.

**Comment by dmulder** [comment]
Thank you!

**Pull request merged**
