### PR TITLE
Adding OpenJDK to openSUSE s390x container-images

### PR DESCRIPTION
**Pull request by hrauchgh**
This is my 1st draft of OpenJDK LTS images for s390x

### CODE REVIEW

**Comment by skriesch** [comment]
@sysrich, @thkukuk: Can you review and accept this PR, please?

**Comment by thkukuk** [comment]
I find the name of the PR a little bit misleading, as it is not s390x specific.
The anchore-analysis.yml should be a separate PR and not hidden in another independent one. This is something which may need more discussions.
And last, we have already: https://build.opensuse.org/package/show/devel:kubic:containers/java11-devel-container
Why do we need the next variant of this?

**Comment by skriesch** [comment]
These java container images are only available for PowerPC and aarch64. We want to provide container images for s390x and other architectures, too.

This repository was referenced  for Dockerfile based builds in OBS and there was no directory for that until now. Therefore, my suggestion was to add them here.

I agree, that anchore-analysis.yml is independent of this PR. My colleague Holger is new and wanted to contribute an additional improvement.
@HolgerRauch Can you remove this yml file again and create a separate PR, please?

**Comment by thkukuk** [comment]
The containers from the devel:kubic:containers project are available for all architectures, including s390x (Ok, s390x is far behind because it's still waiting that the java packages get all build).
The official containers are only available for i586 and x86-64. 
I don't know where you see java containers only available for ppc64 and aarch64. To me, it looks like someody only needs to enable the existing containers in Factory for the other architectures instead of creating new ones, which still would not be published elsewhere, if they don't get enabled...

The workflow for containers is the same as for every other package: there must be a devel project, from there it needs to be submitted to Factory, from where it will be released (in the container case into registry.opensuse.org). This project is only to have a place to develop things in github before transfering via service files or whatever into OBS.

**Comment by sysrich** [comment]
The java11-devel-container is in openSUSE:Factory:zSystems already

https://build.opensuse.org/package/show/openSUSE:Factory:zSystems/java11-devel-container

This PR does nothing s390x related nor does it do anything to address any issues with the java11-devel-container image that is already in Factory:zSystems.

This image certainly seemed to build fine 5 days ago:
https://build.opensuse.org/package/binary/openSUSE:Factory:zSystems/java11-devel-container/containerfile/s390x/opensuse-openjdk-11.s390x-1.32.containerinfo and what looks to be to be an appropriate tarball is certainly downloadable from OBS:
https://build.opensuse.org/package/binary/download/openSUSE:Factory:zSystems/java11-devel-container/containerfile/s390x/opensuse-openjdk-11.s390x-1.32.tar

If there is a problem publishing that image for zSystems that might be an issue for the Release Team of the zSystems port, or the OBS Team, but this PR would do nothing to address such a problem.

Hope this helps.

**Comment by skriesch** [comment]
Thank you for this hint! It does not seem to be transferred to https://registry.opensuse.org/cgi-bin/cooverview.
We wanted to enable existing images first.

**Comment by hrauchgh** [comment]
Thanks for the hints. I wasn't aware of the exact process you outlined.

**Comment by thkukuk** [comment]
See comment from Richard from [17 Aug 2021](https://github.com/openSUSE/container-images/pull/1#issuecomment-900223672)

**Pull request closed without merging**
