### PR TITLE
samba-ad-dc: add ldb-tools to container

### PR DESCRIPTION
**Pull request by dmulder**

### CODE REVIEW

**Comment by dmulder** [comment]
Fixes #9

**Comment by dmulder** [comment]
@mikelpr look good to you?

**Comment by fatmalama** [comment]
@dmulder yes, it looks good. sorry I didn't do the PR, I was having burnout and it didn't come to my mind, thanks a lot <3
(also I had already commented this but maybe it failed. or maybe one of you deleted it in which case you're free to do so again, lol.)

**Comment by dmulder** [comment]
> (also I had already commented this but maybe it failed. or maybe one of you deleted it in which case you're free to do so again, lol.)

Hrm, if your comment got deleted it was probably a mistake.

**Pull request merged**
